name: .NET CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - run: dotnet restore
    - run: dotnet build --no-restore --configuration Release
    - run: dotnet test --no-build --verbosity normal